FROM node:14-alpine

# Copy composer.lock and composer.json
COPY  ./node/package.json /var/www/node/

# Set working directory
WORKDIR /var/www/node

EXPOSE 3000

RUN npm i
COPY ./node /var/www/node/
CMD ["node", "bin/www"]